# Mongo DB headless service
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongodb