# Nodeport service for the yoloapp node
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: Nodeport 
  selector:
    app: yoloapp
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 3000

 